////
//// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
//// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//// Any modifications to this file will be lost upon recompilation of the source schema. 
//// Generated on: 2018.03.11 at 01:57:09 PM ICT 
////
//
//
//package entities;
//
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlAttribute;
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlRootElement;
//import javax.xml.bind.annotation.XmlType;
//
//
///**
// * <p>Java class for anonymous complex type.
// * 
// * <p>The following schema fragment specifies the expected content contained within this class.
// * 
// * <pre>
// * &lt;complexType>
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;element name="CategoryName" type="{www.namectgr.vn}Name"/>
// *       &lt;/sequence>
// *       &lt;attribute name="CategoryId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// * 
// * 
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "", propOrder = {
//    "categoryName"
//})
//@XmlRootElement(name = "Category")
//public class Category {
//
//    @XmlElement(name = "CategoryName", required = true)
//    protected Name categoryName;
//    @XmlAttribute(name = "CategoryId", required = true)
//    protected String categoryId;
//
//    /**
//     * Gets the value of the categoryName property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link Name }
//     *     
//     */
//    public Name getCategoryName() {
//        return categoryName;
//    }
//
//    /**
//     * Sets the value of the categoryName property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link Name }
//     *     
//     */
//    public void setCategoryName(Name value) {
//        this.categoryName = value;
//    }
//
//    /**
//     * Gets the value of the categoryId property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link String }
//     *     
//     */
//    public String getCategoryId() {
//        return categoryId;
//    }
//
//    /**
//     * Sets the value of the categoryId property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *     
//     */
//    public void setCategoryId(String value) {
//        this.categoryId = value;
//    }
//
//}
