/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.10 at 03:08:05 PM ICT 
//


package entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Name.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Name">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Gh\u1ebf Ch\u01a1i Game"/>
 *     &lt;enumeration value="Tay C\u1ea7m Ch\u01a1i Game"/>
 *     &lt;enumeration value="Tai Nghe Ch\u01a1i Game"/>
 *     &lt;enumeration value="B�n Ph�m Ch\u01a1i Game"/>
 *     &lt;enumeration value="B�n Di Chu\u1ed9t Ch\u01a1i Game"/>
 *     &lt;enumeration value="Loa Gaming"/>
 *     &lt;enumeration value="Chu\u1ed9t Ch\u01a1i Game"/>
 *     &lt;enumeration value="Ph\u1ee5 Ki\u1ec7n Gear Gaming"/>
 *     &lt;enumeration value="M�y Game Console"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Name", namespace = "www.namectgr.vn")
@XmlEnum
public enum Name {

    @XmlEnumValue("Gh\u1ebf Ch\u01a1i Game")
    GHẾ_CHƠI_GAME("Gh\u1ebf Ch\u01a1i Game"),
    @XmlEnumValue("Tay C\u1ea7m Ch\u01a1i Game")
    TAY_CẦM_CHƠI_GAME("Tay C\u1ea7m Ch\u01a1i Game"),
    @XmlEnumValue("Tai Nghe Ch\u01a1i Game")
    TAI_NGHE_CHƠI_GAME("Tai Nghe Ch\u01a1i Game"),
    @XmlEnumValue("B\u00e0n Ph\u00edm Ch\u01a1i Game")
    BÀN_PHÍM_CHƠI_GAME("B\u00e0n Ph\u00edm Ch\u01a1i Game"),
    @XmlEnumValue("B\u00e0n Di Chu\u1ed9t Ch\u01a1i Game")
    BÀN_DI_CHUỘT_CHƠI_GAME("B\u00e0n Di Chu\u1ed9t Ch\u01a1i Game"),
    @XmlEnumValue("Loa Gaming")
    LOA_GAMING("Loa Gaming"),
    @XmlEnumValue("Chu\u1ed9t Ch\u01a1i Game")
    CHUỘT_CHƠI_GAME("Chu\u1ed9t Ch\u01a1i Game"),
    @XmlEnumValue("Ph\u1ee5 Ki\u1ec7n Gear Gaming")
    PHỤ_KIỆN_GEAR_GAMING("Ph\u1ee5 Ki\u1ec7n Gear Gaming"),
    @XmlEnumValue("M\u00e1y Game Console")
    MÁY_GAME_CONSOLE("M\u00e1y Game Console");
    private final String value;

    Name(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Name fromValue(String v) {
        for (Name c: Name.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
